// CmdsCam.js
const Cam = Object.freeze({
    PAN_LEFT:                 0,
    PAN_RIGHT:                1,
    TILT_UP:                  2,
    TILT_DOWN:                3,
    PAN_STOP:                 4,
    TILT_STOP:                5,
    ZOOM_TELE:                6,
    ZOOM_WIDE:                7,
    FOCUS_NEAR:               8,
    FOCUS_FAR:                9,
    ZOOM_STOP:               10,
    FOCUS_STOP:              11,
    SET_PERSET:              12,
    GO_TO_PRESET:            13,
    CLEAR_PRESET:            14,
    SET_PRESET_SPEED:        15,
    SET_PRESET_STAY_TIME:    16,
    LOAD_PRESET_FOR_LA:      17,
    SAVE_PRESET_FOR_LA:      18,
    SET_PAN_SPEED:           19,
    SET_TILT_SPEED:          20,
    SET_SYNC_SPEED:          21,
    SET_PAN_POSITION:        22,
    SET_TILT_POSITION:       23,
    SET_ZOOM_POSITION:       24,
    SET_FOCUS_POSITION:      25,
    COLOR_CAM_ON:            26,
    COLOR_CAM_OFF:           27,
    PAN_MOTOR_ON:            28,
    PAN_MOTOR_OFF:           29,
    TILT_MOTOR_ON:           30,
    TILT_MOTOR_OFF:          31,
    HEATER_ON:               32,
    HEATER_OFF:              33,
    COOLER_ON:               34,
    COOLER_OFF:              35,
});


module.exports = Cam;
